server:
  error:
    include-stacktrace: on-param

spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  security:
    token:
      secret: ${JWT.SECRET:my-secret-key}
