services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1996
      POSTGRES_DB: balcao_anuncios_uff
      TZ: "America/Sao_Paulo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/balcao_anuncios_uff
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1996
      API_SECURITY_TOKEN_SECRET: my-secret-key
      GOOGLE_CLIENT_ID: 1080697336488-lqffnqk5lppnqkionbrnit6ubr0hpam6.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/src/main/resources/uploads/images/

volumes:
  postgres_data:
  uploads_data:
