name: Approve Pull Request

on:
  pull_request:
      types: [opened, reopened, labeled]

jobs:
  approve-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label matches
        id: label-check
        run: |
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
          if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q '"ready-to-merge"'; then
            echo "Label found: ready-to-merge"
            echo "approve=true" >> $GITHUB_ENV
          else
            echo "Label not found"
            echo "approve=false" >> $GITHUB_ENV

      - name: Approve Pull Request
        if: env.approve == 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
