name: Merge PR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check and merge'
        required: true
        default: 'main'

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Pull Request Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if PR has the 'ready-to-merge' label..."
          # Busca PR aberta com a branch main como base (destino)
          PR_NUMBER=$(gh pr list --state open --base main --json number -q ".[0].number")
          
          if [[ -z "$PR_NUMBER" ]]; then
            echo "No open PR found with 'main' as the base branch. Exiting."
            exit 1
          fi
          
          echo "PR Number: $PR_NUMBER"
          LABELS=$(gh pr view $PR_NUMBER --json labels -q ".labels[].name")
          echo "Labels: $LABELS"
          
          if [[ "$LABELS" != *"ready-to-merge"* ]]; then
            echo "PR does not have the 'ready-to-merge' label. Exiting."
            exit 1
          fi
          
          echo "PR is ready for merge."
          echo "merge=true" >> $GITHUB_ENV

      - name: Merge Pull Request
        if: env.merge == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Merging PR #$PR_NUMBER..."
          gh pr merge $PR_NUMBER --merge --delete-branch --repo ${{ github.repository }}
          echo "PR #$PR_NUMBER merged successfully!"
