name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configura o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven' # Habilita cache para dependências Maven

    # Instala as dependências e executa os testes
    - name: Build with Maven
      run: mvn clean install -DskipTests=false

    # Publica relatórios de teste (se existirem)
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/

    # Executa a aplicação (opcional)
    - name: Run Application
      if: ${{ github.event_name == 'push' }}
      run: mvn spring-boot:run
