name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1996
          POSTGRES_DB: balcao_anuncios_uff

    steps:
    # Configura o repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Configura o Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    # Aguarda o banco de dados inicializar
    - name: Wait for Postgres
      run: |
        echo "Aguardando inicialização do banco de dados..."
        for i in {1..10}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "Banco de dados está pronto!"
            break
          fi
          echo "Aguardando o banco de dados... Tentativa $i"
          sleep 5
        done

    # Compila o código
    - name: Build with Maven
      run: |
        cd balcao-uff
        mvn clean install -DskipTests=false

    # Publica relatórios de teste
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: balcao-uff/target/surefire-reports/

    # Executa a aplicação
    - name: Run Application
      if: ${{ github.event_name == 'push' }}
      run: |
        cd balcao-uff
        nohup mvn spring-boot:run & echo $! > application.pid

    # Para a aplicação ao final
    - name: Stop Application
      if: ${{ github.event_name == 'push' }}
      run: |
        if [ -f balcao-uff/application.pid ]; then
          kill $(cat balcao-uff/application.pid) || echo "Aplicação já foi encerrada"
        fi
