name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clona o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Lista os arquivos no repositório para verificar a estrutura
    - name: List repository contents
      run: ls -l

    # Configura o Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    # Navega até o diretório do projeto e compila o código
    - name: Build with Maven
      run: |
        cd balcao-uff
        mvn clean install -DskipTests=false

    # Publica relatórios de teste (se existirem)
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: balcao-uff/target/surefire-reports/

    # Executa a aplicação (opcional)
    - name: Run Application
      if: ${{ github.event_name == 'push' }}
      run: |
        cd balcao-uff
        mvn spring-boot:run
