name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1996
          POSTGRES_DB: balcao_anuncios_uff

    steps:
    # Configura o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven' # Habilita cache para dependências Maven

    # Aguarda o banco de dados inicializar
    - name: Wait for Postgres
      run: |
        echo "Aguardando inicialização do banco de dados..."
        for i in {1..10}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "Banco de dados está pronto!"
            break
          fi
          echo "Aguardando o banco de dados... Tentativa $i"
          sleep 5
        done

    # Navega até o diretório do projeto e compila o código
    - name: Build with Maven
      run: |
        cd balcao-uff
        mvn clean install -DskipTests=false

    # Publica relatórios de teste (se existirem)
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: balcao-uff/target/surefire-reports/

    # Executa a aplicação (opcional)
    - name: Run Application
      if: ${{ github.event_name == 'push' }}
      run: |
        cd balcao-uff
        mvn spring-boot:run
